<?php

namespace App\Modules\Jukebox\Providers;

use App;
use Lang;
use View;
use Blade;
use Config;
use App\Modules\Jukebox\Models\Album;
use App\Modules\Jukebox\Models\Song;
use Caffeinated\Modules\Support\ServiceProvider;

class JukeboxServiceProvider extends ServiceProvider
{
	/**
	 * Register the Jukebox module service provider.
	 *
	 * This service provider is a convenient place to register your modules
	 * services in the IoC container. If you wish, you may make additional
	 * methods or service providers to keep the code more focused and granular.
	 *
	 * @return void
	 */
	public function register()
	{
		App::register('App\Modules\Jukebox\Providers\RouteServiceProvider');

		Lang::addNamespace('jukebox', realpath(__DIR__.'/../Resources/Lang'));
		View::addNamespace('jukebox', base_path('resources/views/vendor/jukebox'));
		View::addNamespace('jukebox', realpath(__DIR__.'/../Resources/Views'));
	}

	/**
	 * Bootstrap the application events.
	 *
	 * Here you may register any additional middleware provided with your
	 * module with the following addMiddleware() method. You may pass in
	 * either an array or a string.
	 *
	 * @return void
	 */
	public function boot()
	{
		// $this->addMiddleware('');

        Blade::directive('datetime', function ($expression) {
            return "<?php echo explode(' ', trim({$expression}, '()'))[0]; ?>";
        });

        Blade::directive('filesize', function ($expression) {
            return "<?php echo '[' . round({$expression} / 1024 / 1024, 2) . 'M]'; ?>";
        });

        Album::saved(function () { return response()->json('成功上传!'); });
        Song::saved(function () { return response()->json('成功上传!'); });
	}

	/**
	 * Additional Compiled Module Classes
	 *
	 * Here you may specify additional classes to include in the compiled file
	 * generated by the `artisan optimize` command. These should be classes
	 * that are included on basically every request into the application.
	 *
	 * @return array
	 */
	public static function compiles()
	{
		$basePath = realpath(__DIR__.'/../');

		return [
			// $basePath.'/example.php',
		];
	}
}
